version: 2

sources:
  - name: raw
    database: miguel-490720
    schema: miguel_block3
    tables:
      - name: raw_orders
        identifier: raw_orders
      - name: raw_customers
        identifier: raw_customers
      - name: raw_order_items
        identifier: raw_order_items
      - name: raw_products
        identifier: raw_products
