default:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: miguel-490720
      dataset: miguel_block3
      threads: 1
      keyfile: C:\Users\migue\Downloads\key.json